/**
 * Templates for the files `kody init` writes into the target directory.
 *
 * Kept dependency-free: every template is a plain string so the binary
 * doesn't need to read from disk at runtime. The output is intentionally
 * short and annotated so a human can read the generated files.
 */

export interface InitOptions {
  siteId: string;
  baseUrl: string;
  model: string;
  apiKey: string;
  origin: string;
  adminEmail: string;
  adminPassword: string;
  serverPort: number;
}

export interface GeneratedFile {
  /** Path relative to the target server dir, forward-slash separated. */
  relativePath: string;
  contents: string;
}

const SITE_ID_REGEX = /^[a-z0-9-]+$/;

/** Site id rule, mirrored from `packages/shared/src/validators/site-config.ts`. */
export function isValidSiteId(id: string): boolean {
  return SITE_ID_REGEX.test(id) && id.length >= 1 && id.length <= 100;
}

/** Provider presets the CLI offers during interactive `init`. */
export const AI_PROVIDER_PRESETS = [
  { label: "OpenAI", baseUrl: "https://api.openai.com/v1", exampleKey: "sk-..." },
  { label: "Ollama (local)", baseUrl: "http://localhost:11434/v1", exampleKey: "ollama" },
  { label: "vLLM (local)", baseUrl: "http://localhost:8000/v1", exampleKey: "EMPTY" },
  { label: "llama.cpp server", baseUrl: "http://localhost:8080/v1", exampleKey: "EMPTY" },
] as const;

export function renderEnvFile(opts: InitOptions): string {
  return `# Generated by \`npx kody init\`.
# Copy to \`.env\` and edit secrets before deploying.
PORT=${opts.serverPort}
NODE_ENV=production
DATABASE_PATH=./data/kody.db

# AI provider
AI_BASE_URL=${opts.baseUrl}
AI_MODEL=${opts.model}
AI_API_KEY=${opts.apiKey}

# Site id this server is configured for. Used by the dev seed.
SITE_ID=${opts.siteId}
ALLOWED_ORIGIN=${opts.origin}

# Admin login (used on first boot to create the admin user)
ADMIN_EMAIL=${opts.adminEmail}
ADMIN_PASSWORD=${opts.adminPassword}
`;
}

export function renderDockerCompose(opts: InitOptions): string {
  return `# Generated by \`npx kody init\`.
# Drop into your project root and \`docker compose up -d\`.
services:
  server:
    image: ghcr.io/chafficui/kody:latest
    ports:
      - "${opts.serverPort}:${opts.serverPort}"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/kody.db
    volumes:
      - kody_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${opts.serverPort}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  kody_data:
`;
}

export function renderEmbedSnippet(opts: InitOptions): string {
  // Escape any quotes in the origin for the HTML attribute.
  const safeOrigin = opts.origin.replace(/"/g, "&quot;");
  return `<!-- Drop into the <body> of any page on ${safeOrigin} -->
<script src="${opts.origin.replace(/\/$/, "")}/widget.js"
        data-site-id="${opts.siteId}"
        async></script>
`;
}

export function renderReadme(opts: InitOptions): string {
  return `# Kody server (${opts.siteId})

This directory was scaffolded by \`npx kody init\`.

## Run locally

\`\`\`bash
docker compose up -d
\`\`\`

The server will be available at \`${opts.origin}\`.

- Admin dashboard: \`${opts.origin}/admin\`
- Health check: \`${opts.origin}/health\`
- API spec: \`${opts.origin}/openapi.yaml\`

## Embed the widget

\`\`\`html
<script src="${opts.origin.replace(/\/$/, "")}/widget.js" data-site-id="${opts.siteId}" async></script>
\`\`\`

## Verify

\`\`\`bash
npx kody doctor --server-url ${opts.origin}
\`\`\`

## Reconfigure

Edit \`.env\`, then \`docker compose up -d --force-recreate\`.
For site-config changes (branding, guardrails, knowledge), use the admin UI.
`;
}

/** All files `init` writes, in the order they should be created. */
export function generateFiles(opts: InitOptions): GeneratedFile[] {
  return [
    { relativePath: ".env.example", contents: renderEnvFile(opts) },
    { relativePath: "docker-compose.yml", contents: renderDockerCompose(opts) },
    { relativePath: "EMBED.md", contents: renderEmbedSnippet(opts) },
    { relativePath: "README.md", contents: renderReadme(opts) },
  ];
}
