/**
 * Templates for the files `kody init` writes into the target directory.
 *
 * Kept dependency-free: every template is a plain string so the binary
 * doesn't need to read from disk at runtime. The output is intentionally
 * short and annotated so a human can read the generated files.
 */

export interface InitOptions {
  siteId: string;
  baseUrl: string;
  model: string;
  apiKey: string;
  /** Customer's website origin (used for CORS and the embed snippet). */
  origin: string;
  adminEmail: string;
  adminPassword: string;
  serverPort: number;
  /** Base URL of the Kody server itself, e.g. http://localhost:3456. */
  serverUrl: string;
}

export interface GeneratedFile {
  /** Path relative to the target server dir, forward-slash separated. */
  relativePath: string;
  contents: string;
}

const SITE_ID_REGEX = /^[a-z0-9-]+$/;

/** Site id rule, mirrored from `packages/shared/src/validators/site-config.ts`. */
export function isValidSiteId(id: string): boolean {
  return SITE_ID_REGEX.test(id) && id.length >= 1 && id.length <= 100;
}

/** Provider presets the CLI offers during interactive `init`. */
export const AI_PROVIDER_PRESETS = [
  { label: "OpenAI", baseUrl: "https://api.openai.com/v1", exampleKey: "sk-..." },
  { label: "Ollama (local)", baseUrl: "http://localhost:11434/v1", exampleKey: "ollama" },
  { label: "vLLM (local)", baseUrl: "http://localhost:8000/v1", exampleKey: "EMPTY" },
  { label: "llama.cpp server", baseUrl: "http://localhost:8080/v1", exampleKey: "EMPTY" },
] as const;

/**
 * Quote a value for use inside a `.env` file.
 *
 * Why: passwords and API keys frequently contain characters that are
 * special to shell-style parsers (# comments, trailing whitespace,
 * embedded newlines, single quotes). We single-quote the value and
 * escape any embedded apostrophe with a backslash inside the outer
 * single quotes (Compose / dotenv convention: `'\''` -> `\'`).
 *
 * The Compose convention is preferred over the shell `'\\''` trick
 * because docker-compose's env interpolation does not run through a
 * shell — it sees the raw bytes between the outer single quotes and
 * needs the backslash to actually land in the parsed value, not get
 * swallowed by a shell-pass.
 */
function quoteEnvValue(value: string): string {
  const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
  return `'${escaped}'`;
}

/** Render a `.env.example` with placeholders. Safe to commit. */
export function renderEnvExample(opts: InitOptions): string {
  return `# Generated by \`npx kody init\`.
# Copy to \`.env\` and edit secrets before deploying.
PORT=${opts.serverPort}
NODE_ENV=production
DATABASE_PATH=./data/kody.db

# AI provider
AI_BASE_URL=${opts.baseUrl}
AI_MODEL=${opts.model}
AI_API_KEY='replace-with-your-provider-key'

# Site id this server is configured for. Used by the dev seed.
SITE_ID=${opts.siteId}
ALLOWED_ORIGIN=${opts.origin}

# Admin login (used on first boot to create the admin user)
ADMIN_EMAIL=${opts.adminEmail}
ADMIN_PASSWORD='change-me-to-a-strong-secret'
`;
}

/** Render the live `.env` with the values the user actually supplied. */
export function renderEnvFile(opts: InitOptions): string {
  return `# Generated by \`npx kody init\`.
# Live values — do NOT commit this file. .env is in .gitignore.
PORT=${opts.serverPort}
NODE_ENV=production
DATABASE_PATH=./data/kody.db

# AI provider
AI_BASE_URL=${opts.baseUrl}
AI_MODEL=${opts.model}
AI_API_KEY=${quoteEnvValue(opts.apiKey)}

# Site id this server is configured for. Used by the dev seed.
SITE_ID=${opts.siteId}
ALLOWED_ORIGIN=${opts.origin}

# Admin login (used on first boot to create the admin user)
ADMIN_EMAIL=${opts.adminEmail}
ADMIN_PASSWORD=${quoteEnvValue(opts.adminPassword)}
`;
}

/** Render a starter `.gitignore` so the live `.env` never leaks into VCS. */
export function renderEnvGitignore(): string {
  return `# Generated by \`npx kody init\`.
# Kody runtime state — never commit.
.env
data/
node_modules/
`;
}

export function renderDockerCompose(opts: InitOptions): string {
  return `# Generated by \`npx kody init\`.
# Drop into your project root and \`docker compose up -d\`.
services:
  server:
    image: ghcr.io/chafficui/kody:latest
    ports:
      - "${opts.serverPort}:${opts.serverPort}"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/kody.db
    volumes:
      - kody_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${opts.serverPort}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  kody_data:
`;
}

/**
 * Escape a string so it is safe to interpolate into an HTML attribute
 * value (double-quoted). Covers the five characters XML cares about:
 *   &  <  >  "  '
 */
function escapeHtmlAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function renderEmbedSnippet(opts: InitOptions): string {
  // Always point the widget at the Kody server's own URL, not the
  // customer's website origin. The server enforces CORS via the origin
  // header against `allowedOrigins` separately.
  const widgetSrc = `${opts.serverUrl.replace(/\/$/, "")}/widget.js`;
  return `<!-- Drop into the <body> of any page on ${escapeHtmlAttr(opts.origin)} -->
<script src="${escapeHtmlAttr(widgetSrc)}"
        data-site-id="${escapeHtmlAttr(opts.siteId)}"
        async></script>
`;
}

export function renderReadme(opts: InitOptions): string {
  return `# Kody server (${opts.siteId})

This directory was scaffolded by \`npx kody init\`.

The Kody server listens on **${opts.serverUrl}** (your customer's site
is at **${opts.origin}** — they are usually different).

## Run locally

\`\`\`bash
docker compose up -d
\`\`\`

The server will be available at \`${opts.serverUrl}\`.

- Admin dashboard: \`${opts.serverUrl}/admin\`
- Health check: \`${opts.serverUrl}/health\`
- API spec: \`${opts.serverUrl}/openapi.yaml\`

## Embed the widget

Add this snippet to a page on \`${opts.origin}\`:

\`\`\`html
<script src="${opts.serverUrl.replace(/\/$/, "")}/widget.js" data-site-id="${escapeHtmlAttr(opts.siteId)}" async></script>
\`\`\`

## Verify

\`\`\`bash
npx kody doctor --server-url ${opts.serverUrl}
\`\`\`

## Reconfigure

Edit \`.env\`, then \`docker compose up -d --force-recreate\`.
For site-config changes (branding, guardrails, knowledge), use the admin UI.
`;
}

/** All files `init` writes, in the order they should be created. */
export function generateFiles(opts: InitOptions): GeneratedFile[] {
  return [
    // .env.example is the safe-to-commit template (placeholders only).
    // .env holds the user's real secrets and is covered by the .gitignore
    // we also write. Splitting the two means a fresh `init` over an
    // already-cloned repo does not commit anyone's live credentials.
    { relativePath: ".env.example", contents: renderEnvExample(opts) },
    { relativePath: ".env", contents: renderEnvFile(opts) },
    { relativePath: ".gitignore", contents: renderEnvGitignore() },
    { relativePath: "docker-compose.yml", contents: renderDockerCompose(opts) },
    { relativePath: "EMBED.md", contents: renderEmbedSnippet(opts) },
    { relativePath: "README.md", contents: renderReadme(opts) },
  ];
}
